console.log;
console.log.bind;
console.warn;
console.warn.bind;
console.error;
console.error.bind;
console.group;
console.group.bind;
console.groupEnd;
console.groupEnd.bind;
var encodeURIComponent;
var decodeURIComponent;
Window.alert;
Window.prototype.setTimeout;
Window.prototype.onmessage;
Window.prototype.postMessage;
var Phaser;
Phaser.ScaleManager;
Phaser.ScaleManager.RESIZE;
Phaser.Game;
Phaser.Game.prototype.load;
Phaser.Game.prototype.load.image;
Phaser.Game.prototype.load.spritesheet;
Phaser.Game.prototype.add;
Phaser.Game.prototype.add.button;
Phaser.Game.prototype.add.sprite;
Phaser.Game.prototype.add.image;
Phaser.Game.prototype.add.tween;
Phaser.Game.prototype.add.text;
Phaser.Game.prototype.stage;
Phaser.Game.prototype.stage.backgroundColor;
Phaser.Game.prototype.cache;
Phaser.Game.prototype.cache.getImage;
Phaser.Sprite;
Phaser.Sprite.prototype.scale;
Phaser.Sprite.prototype.scale.setTo;
Phaser.Sprite.prototype.anchor;
Phaser.Sprite.prototype.anchor.x;
Phaser.Sprite.prototype.anchor.y;
Phaser.Sprite.prototype.inputEnabled;
Phaser.Sprite.prototype.events;
Phaser.Sprite.prototype.events.onInputDown;
Phaser.Sprite.prototype.events.onInputDown.add;
Phaser.Canvas;
Phaser.Easing;
Phaser.Easing.Linear;
Phaser.Easing.Linear.None;
Phaser.Button;
Phaser.Button.prototype.scale;
Phaser.Button.prototype.scale.setTo;
Phaser.Text;
Phaser.Text.prototype.setShadow;
Phaser.Text.prototype.setText;
Object.scale;
Object.scale.setTo;
Object.anchor;
Object.anchor.x;
Object.anchor.y;
Object.exec;
Object.index;
Object.to;
Object.width;
Object.height;
var MaterialUI;
HTMLDocument.prototype.getElementById;
goog.DEBUG;
goog.string;
goog.string.StringBuffer;
goog.string.StringBuffer.prototype.append;
goog.require;
goog.isArrayLike;
var Image;
Image.prototype.onload;
Image.prototype.width;
Image.prototype.height;
Image.prototype.src;
XMLHttpRequest.prototype.timeout;
XMLHttpRequest.prototype.ajax$protocols$AjaxResponse$_body$arity$1;
XMLHttpRequest.prototype.ajax$protocols$AjaxRequest$;
XMLHttpRequest.prototype.ajax$protocols$AjaxRequest$_abort$arity$1;
XMLHttpRequest.prototype.ajax$protocols$AjaxImpl$;
XMLHttpRequest.prototype.ajax$protocols$AjaxResponse$_was_aborted$arity$1;
XMLHttpRequest.prototype.ajax$protocols$AjaxResponse$_get_response_header$arity$2;
XMLHttpRequest.prototype.ajax$protocols$AjaxResponse$_status_text$arity$1;
XMLHttpRequest.prototype.ajax$protocols$AjaxResponse$;
XMLHttpRequest.prototype.ajax$protocols$AjaxImpl$_js_ajax_request$arity$3;
XMLHttpRequest.prototype.ajax$protocols$AjaxResponse$_status$arity$1;
var process;
process.hrtime;
JSON.parse;
JSON.stringify;
var require;
require.resolve;
window.AudioContext;
window.webkitAudioContext;
var setTimeout;
var MaterialUIStyles;
MaterialUIStyles.getMuiTheme;
var React;
React.createElement;
Console.error;
